#!/bin/bash

#####
## First created by: Jason M. Green
## gitHub:  
## Twitter:  @gJigsaw
##
## Thank you friend for this rather handy script!
#####

if which tmux 2>&1 >/dev/null; then
  # if no session is started, start a new session
  if test -z ${TMUX}; then
    tmux attach || tmux
  fi
#  # when quitting tmux, try to attach
#    while test -z ${TMUX}; do
#      tmux attach || break
#    done
fi
