#!/bin/bash

#####
## I would like to say a special thank you to a good friend and mentor
##  for sharing this rather handy script with me many years ago!
## 
## Original Author by:  Jason Green
## gitHub:  https://github.com/gJigsaw
## Twitter:  @gJigsaw
#####

if which tmux 2>&1 >/dev/null; then
  # if no session is started, start a new session
  if test -z ${TMUX}; then
    tmux attach || tmux
  fi
#  # when quitting tmux, try to attach
#    while test -z ${TMUX}; do
#      tmux attach || break
#    done
fi
